### ISSUE TITLE
Düzenleme yapılacaklar

### ISSUE THREAD

**Issue by cagatayldzz** [netioo/humhub-shdw-theme#1]
- [x] Dashboard 'user-layout' mobil görünüm  için kapatılacak.
- [x] Dashboard 'user-layout' tablet görünüm için kapatılacak.
- [x] #topbar-first .notifications .dropdown-menu li{color: #718b92;} 
- [x] #topbar-first .notifications .dropdown-menu{margin-left:-264px} 
- [x] #topbar-first .notifications .arrow{margin-left:99px;} 
- [x] #topbar-first .notifications .dropdown-menu li{font-weight:100}
- [x] #topbar-second .nav>li>a:hover,#topbar-second .nav>li>a:active,#topbar-second .nav>li>a:focus{border-bottom:3px solid #718b92;background-color:rgba(247, 247, 247, 0.12);color:#fff;text-decoration:none}
- [x] .panel-profile .panel-profile-header .profile-user-photo-container .btn-info{padding:4px 8px}
- [x] .panel-profile .panel-profile-header .btn-info{padding:4px 8px}
- [x] .btn-group.dropdown-navigation{border: 1px solid #b6c3c7;color: #718b92;border-radius:3px;}
- [x] .btn-group.dropdown-navigation .btn-default{background: white;}
- [x] .btn-group.dropdown-navigation .btn-default:hover{background:#718b92;color: #fff !important;}
